import Head from 'next/head';
import * as React from 'react'

import { useSession } from 'next-auth/react';
import { useRouter } from 'next/router';

import { DashboardTabs } from '~/components/DashboardTabs';



export default function Home() {
  const router = useRouter();

  const { status } = useSession({
    required: true,
    onUnauthenticated() {
      router.push('/login').catch((err) => { console.log('error', err) });
    },
  });

  if (status !== 'authenticated') return null;

  return (
    <>
      <Head>
        <title>Trial-Task</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-2">
        <DashboardTabs />
      </main>
    </>
  );
}
